language: python
python:
  - "2.7"
install: 
  - pip install coveralls
script:
  - nosetests --with-coverage
virtualenv:
  system_site_packages: true
script:
  - nosetests --with-cov --cover-package asr --logging-level=INFO
after_success:
  - coveralls